export interface IEditar {
  document: string | null;
  email: string | null;
  phone: string | null;
  names: string | null;
  lastNames: string | null;
  position: string | null;
  gender: string | null;
  birthday: string | null;
  civilStatus: string | null;
  educationLevel: string | null;
  profession: string | null;
  bloodType: string | null;
  company: string | null;
  companyType: string | null;
  baptized: string | null;
  meetingNew: string | null;
  department: string | null;
  city: string | null;
  locality: string | null;
  direction: string | null;
  roles: number[] | null;
}
