export interface IPerfl {
  _id?: string | null;
  document: string | null;
  email: string | null;
  phone: string | null;
  names: string | null;
  lastNames: string | null;
  position: string | null;
  gender: number | null;
  birthday: string | null;
  civilStatus: number | null;
  educationLevel: number | null;
  profession: number | null;
  bloodType: number | null;
  company: boolean | null;
  companyType: number | null;
  baptized: boolean | null;
  meetingNew: boolean | null;
  department: string | null;
  city: string | null;
  picture: string | null;
  locality: string | null;
  direction: string | null;
  church: string | null;
  roles: number[] | null;
}
