export const rolesListSingleText = [
  'Administrador',
  'Pastor',
  'Supervisor',
  'Líder',
  'Persona',
];

export const educationLevels = [
  'Preescolar',
  'Básica Primaria (1-5)',
  'Básica Secundaria (6-9)',
  'Média (10-13)',
  'Técnica Laboral',
  'Técnica Profesional',
  'Tecnológica',
  'Universitaria',
  'Especialización',
  'Maestría',
  'Doctorado'
];

export const documentType: any[] = [
  { val: 'CC', label: 'Cédula de ciudadanía' },
  { val: 'TI', label: 'Tarjeta de identidad' },
  { val: 'PAS', label: 'Pasaporte' },
  { val: 'CE', label: 'Cédula de extrajería' },
  { val: 'PE', label: 'Permiso Especial de Permanencia' },
];

export const bloodType = [ 'A -', 'A +', 'AB -', 'AB +', 'B -', 'B +', 'O -', 'O +' ];

export const professions: any[] = [
  'Prefiero no indicar',
  'Abogado',
  'Actor, Actriz, Artista, Director de Espectáculos',
  'Actuario',
  'Administrador',
  'Aduanero/Agente de Aduanas/Inspectores de Frontera',
  'Aeromozo/Azafata',
  'Agente/Intermediario/Corredor Inmobiliario',
  'Agente de Bolsa',
  'Agente de Inmigración/Migración',
  'Agente de Turismo/Viajes',
  'Agente/Intermediario/Corredor de Seguros',
  'Agricultor, Agrónomo, Agrologo, Arboricultor',
  'albañil, Obrero de Construcción',
  'Ama de Casa',
  'Analista de Sistema y Computación',
  'Antropólogo, Arqueólogo y Etnólogo',
  'Archivero',
  'Armador de Barco',
  'Arquitecto 00020 Artesano',
  'Asistente Social',
  'Autor Literario, Escritor y Crmtico',
  'Avicultor',
  'Bacteriólogo, Farmacólogo, Biólogo, Científico',
  'Basurero/Barrendero',
  'Cajero',
  'Camarero/Barman/Mesero/Chef',
  'Cambista, Compra/Venta de Moneda',
  'Campesino',
  'Capataz',
  'Cargador',
  'Carpintero',
  'Cartero',
  'Cerrajero',
  'Cobrador',
  'Comerciante / Vendedor',
  'Conductor, Chofer / Taxista',
  'Conserje/Portero/Guardián/Vigilante',
  'Constructor',
  'Contador',
  'Contratista',
  'Corte y Confección de Ropa/Fabricante de Prendas',
  'Cosmetólogo, Peluquero y Barbero',
  'Decorador, Dibujante, Publicista',
  'Dentista / Odontólogo',
  'Deportista Profesional, Atleta, Arbitro',
  'Distribuidor',
  'Docente',
  'Economista',
  'Electricista',
  'Empleada(o) del hogar / Nana',
  'Empresario Exportador/Empresario Importador',
  'Enfermero',
  'Ensamblador',
  'Escultor',
  'Estudiante',
  'Fotógrafo/Operadores cámara, cine y tv, locutor',
  'Ganadero',
  'Gasfitero',
  'Historiador',
  'Ingeniero',
  'Interprete, Traductor',
  'Jardinero',
  'Jockey',
  'Joyero y/o Platero / Orfebre',
  'Jubilado / Pensionista',
  'Laboratorista (Técnico)',
  'Liquidador, Reclamaciones/Seguros',
  'Maquinista / Operador de maquinaria',
  'Martillero / Subastador',
  'Mayorista, comercio al por mayor',
  'Mecánico',
  'Medico / Cirujano',
  'Metalurgista',
  'Miembro de las Fuerzas Armadas',
  'Nutricionista',
  'Obrero / Operador',
  'Obstetriz',
  'Organizador de Eventos',
  'Panadero / Pastelero',
  'Paramédico',
  'Periodista',
  'Perito',
  'Pescador',
  'Piloto',
  'Pintor',
  'Policía Municipal',
  'Policía PNP',
  'Productor de Cine / Radio / Televisión / Teatro',
  'Productor, Cultivos Extensivos',
  'Programador',
  'Psicólogo / Terapeuta',
  'Quiropráctico/Kinesiterapeuta (Kinesiólogos)',
  'Relacionista Publico e Industrial',
  'Relojero',
  'Reparación de Automóviles, Pintor Retocador',
  'Reparador de Aparatos Electrodomésticos',
  'Repartidor',
  'Sacerdote/Monja',
  'Secretaria, Recepcionista, Telefonista',
  'Seguridad/Guardaespaldas/Guardia de Seguridad',
  'Servicio de Almacenamiento/Almacenero',
  'Servicio de Alquiler de Vehículos',
  'Servicios de Alquiler de Videos, Equipos de Sonido',
  'Sociólogo',
  'Tasador',
  'Técnico',
  'Torero',
  'Tramitador',
  'Transporte de Carga y/o Mudanza',
  'Transportista',
  'Vendedor Ambulante',
  'Veterinario, Zoólogo, Zootécnico',
  'Visitador Medico',
  'Zapatero',
  'Otros',
];

export const companyType: string[] = [
  'Empresa asociativa de trabajo',
  'Empresa unipersonal',
  'Persona natural comerciante',
  'Sociedad anónima',
  'Sociedad colectiva',
  'Sociedad en comandita por acciones',
  'Sociedad en comandita simple',
  'Sociedad limitada',
  'Sociedades agrarias de transformación',
  'Sociedades por acciones simplificadas',
  'Otro',
];

export const civilStatus: string[] = [
  'Soltero',
  'Casado',
  'Divorciado',
  'Separado',
  'Prefiero no indicar',
];

export const gender: string[] = [
  'Hombre',
  'Mujer',
  'Prefiero no indicar',
];
